sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.0.104
    port: 3306
    database: sky_take_out
    username: need
    password: 123456
  alioss:
    bucket-name: sky-java-spring
    endpoint: oss-cn-hangzhou.aliyuncs.com
  redis:
    password: 123456
    host: localhost
    port: 6379
    database: 10